---
# This file is used by developers who use ./scripts/deploy.sh to set up a local
# development environment to help with development this module.
version: '2'

services:
  drupal:
    build:
      context: .
      dockerfile: DevelopmentDockerfile9
    volumes:
      - ".:/var/www/html/modules/custom/word_monitor"
    ports:
      - "80"
    links:
      - mysql:mysql
    working_dir: /var/www/html

  mysql:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: drupal

# Specifying the network name makes it predictable on all environments,
# for example when we run browser tests.
# See https://github.com/docker/compose/issues/3736.
networks:
  default:
    external:
      name: word_monitor_default
