<?php

/**
 * @file
 * Runtime hooks.
 */

use Drupal\word_monitor_search\WordMonitorSearch;

/**
 * Quick access to the word_monitor_search service, useful for debugging.
 *
 * @return \Drupal\word_monitor_search\WordMonitorSearch
 *   The WordMonitor service.
 */
// @codingStandardsIgnoreStart
// PHP Lint wants this to be prefixed with the module name, but it _is_
// the same as the module name, so I consider this ok.
function word_monitor_search() : WordMonitorSearch {
// @codingStandardsIgnoreEnd
  return \Drupal::service('word_monitor_search');
}
