<?php

/**
 * @file
 * Runtime hooks.
 */

use Drupal\word_monitor_status_warning\WordMonitorStatusWarning;

/**
 * Quick access to the word_monitor_status_warning service, for debugging.
 *
 * @return \Drupal\word_monitor_status_warning\WordMonitorStatusWarning
 *   The word_monitor_status_warning service.
 */
// @codingStandardsIgnoreStart
// PHP Lint wants this to be prefixed with the module name, but it _is_
// the same as the module name, so I consider this ok.
function word_monitor_status_warning() : WordMonitorStatusWarning {
// @codingStandardsIgnoreEnd
  return \Drupal::service('word_monitor_status_warning');
}
